/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "messages_status": {
        "USER_NOT_FOUND": string;
        "USER_ALREADY_EXISTS": string;
        "INVALID_EMAIL_OR_PASSWORD": string;
        "EMAIL_NOT_VERIFIED": string;
        "SESSION_EXPIRED": string;
        "CREDENTIAL_ACCOUNT_NOT_FOUND": string;
        "FAILED_TO_CREATE_SESSION": string;
        "FAILED_TO_GET_SESSION": string;
        "FAILED_TO_CREATE_USER": string;
        "FAILED_TO_UPDATE_USER": string;
        "EMAIL_CAN_NOT_BE_UPDATED": string;
        "USER_EMAIL_NOT_FOUND": string;
        "SOCIAL_ACCOUNT_ALREADY_LINKED": string;
        "PROVIDER_NOT_FOUND": string;
        "FAILED_TO_GET_USER_INFO": string;
        "INVALID_TOKEN": string;
        "ID_TOKEN_NOT_SUPPORTED": string;
        "FAILED_TO_UNLINK_LAST_ACCOUNT": string;
        "INVALID_TWO_FACTOR_COOKIE": string;
        "TWO_FACTOR_NOT_ENABLED": string;
        "OTP_NOT_ENABLED": string;
        "OTP_HAS_EXPIRED": string;
        "TOTP_NOT_ENABLED": string;
        "BACKUP_CODES_NOT_ENABLED": string;
        "INVALID_BACKUP_CODE": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
